language: php

env:
    global:
        - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
        - TASK_STATIC_ANALYSIS=0

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        -   php: "7.2"
        -   php: "7.3"
            env:
                - TASK_STATIC_ANALYSIS=1
        -   php: nightly

    allow_failures:
        -   php: nightly

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug is not installed"

install:
    - travis_retry composer self-update
    - travis_retry composer global require hirak/prestissimo
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - travis_retry composer install $DEFAULT_COMPOSER_FLAGS
    - pecl install ast

before_script:
    # show some versions and env information
    - php --version
    - composer --version

script:
    - phpdbg -qrr vendor/bin/phpunit --verbose --coverage-clover=coverage.clover
    - |
        if [ $TASK_STATIC_ANALYSIS == 1 ]; then
          composer phan
          cat analysis.txt
        fi

after_script:
    - travis_retry wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
